name: Build

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      
      # We do this manually because of course we want to build the tap from the current commit.
    - name: Install the tap
      run: |
        mkdir -p $(brew --repo)/Library/Taps/nativeos
        ln -s $PWD $(brew --repo)/Library/Taps/nativeos/homebrew-i386-elf-toolchain
        brew tap --repair
    - name: Build i386-elf-binutils
      run: brew install i386-elf-binutils
    - name: Test i386-elf-binutils
      run: brew test i386-elf-binutils
    - name: Build i386-elf-gcc
      run: brew install i386-elf-gcc
    - name: Test i386-elf-gcc
      run: brew test i386-elf-gcc
